package com.marcnuri.demo.chucknorris;

import java.util.Arrays;
import java.util.Random;

public class Quotes {

  private static final String[] QUOTES = new String[]{
    "\"It works on my machine\" always holds true for Chuck Norris.",
    "\"Let the Bodies Hit the Floor\" was originally written as Chuck Norris' theme song.",
    "4 out of 5 doctors fail to recommend Chuck Norris as a solution to most problems. Also, 80% of doctors die unexplained, needlessly brutal deaths.",
    "70% of a human's weight is water. 70% of Chuck Norris' weight is his dick.",
    "A handicapped parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there.",
    "A high tide means Chuck Norris is flying over your coast. The tide is caused by God pissing his pants.",
    "A man once asked Chuck Norris if his real name is \"Charles\". Chuck Norris did not respond, he simply stared at him until he exploded.",
    "A man once taunted Chuck Norris with a bag of Lay's potato chips, saying \"Betcha can't eat just one!\" Chuck Norris proceeded to eat the chips, the bag, and the man in one deft move.",
    "A study showed the leading causes of death in the United States are: 1. Heart disease, 2. Chuck Norris, 3. Cancer",
    "According to Einstein's theory of relativity, Chuck Norris can actually roundhouse kick you yesterday.",
    "According to the Encyclopedia Britannica, the Native American \"Trail of Tears\" has been redefined as anywhere that Chuck Norris walks.",
    "After returning from World War 2 unscratched, Bob Dole was congratulated by Chuck Norris with a handshake. The rest is history.",
    "All browsers support the hex definitions #chuck and #norris for the colors black and blue.",
    "All roads lead to Chuck Norris. And by the transitive property, a roundhouse kick to the face.",
    "An anagram for Walker Texas Ranger is KARATE WRANGLER SEX. I don't know what that is, but it sounds AWESOME.",
    "Archaeologists unearthed an old english dictionary dating back to the year 1236. It defined \"victim\" as \"one who has encountered Chuck Norris\"",
    "As President Roosevelt said: \"We have nothing to fear but fear itself. And Chuck Norris.\"",
    "Bill Gates thinks he's Chuck Norris. Chuck Norris actually laughed. Once.",
    "Chuck Norris already went to Moon and Mars, that's why there are no signs of life.",
    "Chuck Norris and Mr. T walked into a bar. The bar was instantly destroyed, as that level of awesome cannot be contained in one building.",
    "Chuck Norris brushes his teeth with a mixture of iron shavings, industrial paint remover, and wood-grain alcohol.",
    "Chuck Norris built the hospital he was born in.",
    "Chuck Norris can be unlocked on the hardest level of Tekken. But only Chuck Norris is skilled enough to unlock himself. Then he roundhouse kicks the Playstation back to Japan.",
    "Chuck Norris can binary search unsorted data.",
    "Chuck Norris can blow bubbles with beef jerky.",
    "Chuck Norris can download emails with his pick-up.",
    "Chuck Norris can drink an entire gallon of milk in thirty-seven seconds.",
    "Chuck Norris can drown a fish.",
    "Chuck Norris can install a 64 bit OS on 32 bit machines.",
    "Chuck Norris can install iTunes without installing Quicktime.",
    "Chuck Norris can instantiate an abstract class.",
    "Chuck Norris can judge a book by its cover.",
    "Chuck Norris can kick through all 6 degrees of separation, hitting anyone, anywhere, in the face, at any time.",
    "Chuck Norris can make onions cry.",
    "Chuck Norris can retrieve anything from /dev/null.",
    "Chuck Norris can slam a revolving door.",
    "Chuck Norris can spawn threads that complete before they are started.",
    "Chuck Norris can speak Braille.",
    "Chuck Norris can stand on his head. His dick-head.",
    "Chuck Norris can taste lies.",
    "Chuck Norris can touch MC Hammer.",
    "Chuck Norris can win a game of Connect Four in only three moves.",
    "Chuck Norris can win a game of Trivial Pursuit with one roll of the dice, and without answering a single question... just a nod of the head, and a stroke of the beard.",
    "Chuck Norris can win in a game of Russian roulette with a fully loaded gun.",
    "Chuck Norris can write infinite recursion functions and have them return.",
    "Chuck Norris can write multi-threaded applications with a single thread.",
    "Chuck Norris can write to an output stream.",
    "Chuck Norris can't finish a \"color by numbers\" because his markers are filled with the blood of his victims. Unfortunately, all blood is dark red.",
    "Chuck Norris can't test for equality because he has no equal.",
    "Chuck Norris cannot love, he can only not kill.",
    "Chuck Norris compresses his files by doing a flying round house kick to the hard drive.",
    "Chuck Norris could use anything in java.util.* to kill you, including the javadocs.",
    "Chuck Norris describes human beings as \"a sociable holder for blood and guts\".",
    "Chuck Norris destroyed the periodic table, because Chuck Norris only recognizes the element of surprise.",
    "Chuck Norris did in fact, build Rome in a day.",
    "Chuck Norris did not \"lose\" his virginity, he stalked it and then destroyed it with extreme prejudice.",
    "Chuck Norris died before 20 years, Death doesn't have the courage to tell him yet.",
    "Chuck Norris does infinite loops in 4 seconds.",
    "Chuck Norris does not \"style\" his hair. It lays perfectly in place out of sheer terror.",
    "Chuck Norris does not code in cycles, he codes in strikes.",
    "Chuck Norris does not follow fashion trends, they follow him. But then he turns around and kicks their ass. Nobody follows Chuck Norris.",
    "Chuck Norris does not own a house. He walks into random houses and people move.",
    "Chuck Norris does not own a stove, oven, or microwave , because revenge is a dish best served cold.",
    "Chuck Norris does not play the lottery. It doesn't have nearly enough balls.",
    "Chuck Norris does not wear a condom. Because there is no such thing as protection from Chuck Norris.",
    "Chuck Norris does, in fact, live in a round house.",
    "Chuck Norris doesn't age, because time cannot keep up with him.",
    "Chuck Norris doesn't believe in Germany.",
    "Chuck Norris doesn't believe in ravioli. He stuffs a live turtle with beef and smothers it in pig's blood.",
    "Chuck Norris doesn't bowl strikes, he just knocks down one pin and the other nine faint.",
    "Chuck Norris doesn't bug hunt as that signifies a probability of failure, he goes bug killing.",
    "Chuck Norris doesn't cheat death. He wins fair and square.",
    "Chuck Norris doesn't chew gum. Chuck Norris chews tin foil.",
    "Chuck Norris doesn't churn butter. He roundhouse kicks the cows and the butter comes straight out.",
    "Chuck Norris doesn't daydream. He's too busy giving other people nightmares.",
    "Chuck Norris doesn't do Burn Down charts, he does Smack Down charts.",
    "Chuck Norris doesn't have disk latency because the hard drive knows to hurry the hell up.",
    "Chuck Norris doesn't look both ways before he crosses the street... he just roundhouses any cars that get too close.",
    "Chuck Norris doesn't need a debugger, he just stares down the bug until the code confesses.",
    "Chuck Norris doesn't needs try-catch, exceptions are too afraid to raise.",
    "Chuck Norris doesn't play god. Playing is for children.",
    "Chuck Norris doesn't read books. He stares them down until he gets the information he wants.",
    "Chuck Norris doesn't say \"who's your daddy\", because he knows the answer.",
    "Chuck Norris doesn't throw up if he drinks too much. Chuck Norris throws down!",
    "Chuck Norris doesn't use Oracle, he is the Oracle.",
    "Chuck Norris doesn't use reflection, reflection asks politely for his help.",
    "Chuck Norris doesn't win, he allows you to lose.",
    "Chuck Norris eats beef jerky and craps gunpowder. Then, he uses that gunpowder to make a bullet, which he uses to kill a cow and make more beef jerky. Some people refer to this as the \"Circle of Life.\"",
    "Chuck Norris got his drivers license at the age of 16. Seconds.",
    "Chuck Norris has 12 moons. One of those moons is the Earth.",
    "Chuck Norris has a deep and abiding respect for human life... unless it gets in his way.",
    "Chuck Norris has never been in a fight, ever. Do you call one roundhouse kick to the face a fight?",
    "Chuck Norris has to register every part of his body as a separate lethal weapon. His spleen is considered a concealed weapon in over 50 states.",
    "Chuck Norris has two speeds: Walk and Kill.",
    "Chuck Norris has volunteered to remain on earth after the Rapture; he will spend his time fighting the Anti-Christ.",
    "Chuck Norris invented Kentucky Fried Chicken's famous secret recipe with eleven herbs and spices. Nobody ever mentions the twelfth ingredient: Fear.",
    "Chuck Norris invented his own type of karate. It's called Chuck-Will-Kill.",
    "Chuck Norris is currently suing myspace for taking the name of what he calls everything around you.",
    "Chuck Norris is his own line at the DMV.",
    "Chuck Norris is not Irish. His hair is soaked in the blood of his victims.",
    "Chuck Norris is responsible for China's over-population. He hosted a Karate tournament in Beijing and all women within 1,000 miles became pregnant instantly.",
    "Chuck Norris is ten feet tall, weighs two-tons, breathes fire, and could eat a hammer and take a shotgun blast standing.",
    "Chuck Norris is the only man to ever defeat a brick wall in a game of tennis.",
    "Chuck Norris is the only man who has, literally, beaten the odds. With his fists.",
    "Chuck Norris is the only person in the world that can actually email a roundhouse kick.",
    "Chuck Norris is the only person to ever win a staring contest against Ray Charles and Stevie Wonder.",
    "Chuck Norris is the only person who can simultaneously hold and fire FIVE Uzis: One in each hand, one in each foot -- and the 5th one he roundhouse-kicks into the air, so that it sprays bullets.",
    "Chuck Norris is the reason why Waldo is hiding.",
    "Chuck Norris is widely predicted to be first black president. If you're thinking to yourself, \"But Chuck Norris isn't black\", then you are dead wrong. And stop being a racist.",
    "Chuck Norris kills anyone that asks: \"Do you want fries with that?\". Because by now everyone should know that Chuck doesn't want fries with anything. Ever.",
    "Chuck Norris knows Victoria's secret.",
    "Chuck Norris knows everything there is to know - Except for the definition of mercy.",
    "Chuck Norris knows the last digit of pi.",
    "Chuck Norris knows the value of NULL, and he can sort by it too.",
    "Chuck Norris likes his coffee half and half: half coffee grounds, half wood-grain alcohol.",
    "Chuck Norris lost his virginity before his dad did.",
    "Chuck Norris made the sun by rubbing his hands together.",
    "Chuck Norris never goes to the dentist because his teeth are unbreakable. His enemies never go to the dentist because they have no teeth.",
    "Chuck Norris never has to build his program to machine code. Machines have learnt to interpret Chuck Norris code.",
    "Chuck Norris never has to wax his skis because they're always slick with blood.",
    "Chuck Norris never wet his bed as a child. The bed wet itself out of fear.",
    "Chuck Norris once ate a whole cake before his friends could tell him there was a stripper in it.",
    "Chuck Norris once ate an entire bottle of sleeping pills. They made him blink.",
    "Chuck Norris once ate four 30lb bowling balls without chewing.",
    "Chuck Norris once ate three 72 oz. steaks in one hour. He spent the first 45 minutes having sex with his waitress.",
    "Chuck Norris once lost the remote, but maintained control of the TV by yelling at it in between bites of his \"Filet of Child\" sandwich.",
    "Chuck Norris once ordered a steak in a restaurant. The steak did what it was told.",
    "Chuck Norris once participated in the running of the bulls. He walked.",
    "Chuck Norris once pissed in a gas tank of a semi truck as a joke - that truck is now know as Optimus Prime.",
    "Chuck Norris once rode a nine foot grizzly bear through an automatic car wash, instead of taking a shower.",
    "Chuck Norris once round-house kicked a salesman. Over the phone.",
    "Chuck Norris once roundhouse kicked someone so hard that his foot broke the speed of light, went back in time, and killed Amelia Earhart while she was flying over the Pacific Ocean.",
    "Chuck Norris once shat blood - the blood of 11,940 natives he had killed and eaten.",
    "Chuck Norris once sold eBay to eBay on eBay.",
    "Chuck Norris once sued Burger King after they refused to put razor wire in his Whopper Jr, insisting that that actually is \"his\" way.",
    "Chuck Norris once went skydiving, but promised never to do it again. One Grand Canyon is enough.",
    "Chuck Norris once worked as a weatherman for the San Diego evening news. Every night he would make the same forecast: Partly cloudy with a 75% chance of Pain.",
    "Chuck Norris originally appeared in the \"Street Fighter II\" video game, but was removed by Beta Testers because every button caused him to do a roundhouse kick. When asked about this glitch, Norris replied \"That's no glitch.\"",
    "Chuck Norris played Russian Roulette with a fully loaded gun and won.",
    "Chuck Norris plays racquetball with a waffle iron and a bowling ball.",
    "Chuck Norris protocol design method has no status, requests or responses, only commands.",
    "Chuck Norris puts sunglasses on to protect the sun from his eyes.",
    "Chuck Norris sheds his skin twice a year.",
    "Chuck Norris shot the sheriff, but he round house kicked the deputy.",
    "Chuck Norris sits at the stand-up.",
    "Chuck Norris sleeps with a pillow under his gun.",
    "Chuck Norris smells what the Rock is cooking... because the Rock is Chuck Norris' personal chef.",
    "Chuck Norris tears can cure the cancer, but the sad thing is Chuck Norris never cries.",
    "Chuck Norris types with one finger. He points it at the keyboard and the keyboard does the rest.",
    "Chuck Norris understands every definition in the Oxford Thesaurus, except one - \"mercy\".",
    "Chuck Norris used to play baseball. When Babe Ruth was hailed as the better player, Chuck Norris killed him with a baseball bat to the throat. Lou Gehrig got off easy.",
    "Chuck Norris uses a night light. Not because Chuck Norris is afraid of the dark, but the dark is afraid of Chuck Norris.",
    "Chuck Norris uses canvas in IE.",
    "Chuck Norris uses ribbed condoms inside out, so he gets the pleasure.",
    "Chuck Norris was banned from competitive bullriding after a 1992 exhibition in San Antonio, when he rode the bull 1,346 miles from Texas to Milwaukee Wisconsin to pick up his dry cleaning.",
    "Chuck Norris was once in a knife fight, and the knife lost.",
    "Chuck Norris was the original sculptor of Mount Rushmore. He completed the entire project using only a bottle opener and a drywall trowel.",
    "Chuck Norris wipes his ass with chain mail and sandpaper.",
    "Chuck Norris' Internet connection is faster upstream than downstream because even data has more incentive to run from him than to him.",
    "Chuck Norris' dick is so big, it has it's own dick, and that dick is still bigger than yours.",
    "Chuck Norris' house has no doors, only walls that he walks through.",
    "Chuck Norris' programs never exit, they terminate.",
    "Chuck Norris' sperm can be seen with the naked eye. Each one is the size of a quarter.",
    "Chuck Norris' testicles do not produce sperm. They produce tiny white ninjas that recognize only one mission: seek and destroy.",
    "Chuck Norris's OSI network model has only one layer - Physical.",
    "Chuck Norris's beard can type 140 wpm.",
    "Chuck Norris's database has only one table, 'Kick', which he DROPs frequently.",
    "Chuck Norris's first program was kill -9.",
    "Chuck Norris's keyboard has the Any key.",
    "Chuck Norris? roundhouse kick is so powerful, it can be seen from outer space by the naked eye.",
    "Chuck Norris? sperm is so badass, he had sex with Nicole Kidman, and 7 months later she prematurely gave birth to a Ford Excursion.",
    "Contrary to popular belief, there is indeed enough Chuck Norris to go around.",
    "Crime does not pay - unless you are an undertaker following Walker, Texas Ranger, on a routine patrol.",
    "Did you know that Chuck Norris was in every Star Wars movie? He was \"The Force\".",
    "Divide Chuck Norris by zero and you will in fact get one........one bad-ass that is.",
    "Do you know why Baskin Robbins only has 31 flavors? Because Chuck Norris doesn't like Fudge Ripple.",
    "Each hair in Chuck Norris's beard contributes to make the world's largest DDOS.",
    "Every SQL statement that Chuck Norris codes has an implicit \"COMMIT\" in its end.",
    "Every time someone uses the word \"intense\", Chuck Norris always replies \"you know what else is intense?\" followed by a roundhouse kick to the face.",
    "Everybody loves Raymond. Except Chuck Norris.",
    "Fact: Chuck Norris doesn't consider it sex if the woman survives.",
    "Faster than a speeding bullet... More powerful than a locomotive... Able to leap tall buildings in a single bound... These are some of Chuck Norris's warm-up exercises.",
    "Fear is not the only emotion Chuck Norris can smell. He can also detect hope, as in \"I hope I don't get a roundhouse kick from Chuck Norris.\"",
    "For some, the left testicle is larger than the right one. For Chuck Norris, each testicle is larger than the other one.",
    "Godzilla is a Japanese rendition of Chuck Norris' first visit to Tokyo.",
    "Google won't search for Chuck Norris because it knows you don't find Chuck Norris, he finds you.",
    "Guantanamo Bay, Cuba, is the military code-word for \"Chuck Norris' basement\".",
    "He who lives by the sword, dies by the sword. He who lives by Chuck Norris, dies by the roundhouse kick.",
    "How many Chuck Norris require to screw a light bulb? None, he will screw it all.",
    "How many roundhouse kicks does it take to get to the center of a tootsie pop? Just one. From Chuck Norris.",
    "How much wood would a woodchuck chuck if a woodchuck could Chuck Norris? All of it.",
    "If Chuck Norris wants your opinion, he'll beat it into you.",
    "If Chuck Norris writes code with bugs, the bugs fix themselves.",
    "If at first you don't succeed, you're not Chuck Norris.",
    "If tapped, a Chuck Norris roundhouse kick could power the country of Australia for 44 minutes.",
    "If you rearrange the letters in \"Chuck Norris\", they also spell \"Crush Rock In\". The words \"with his fists\" are understood.",
    "If you try to kill -9 Chuck Norris's programs, it backfires.",
    "In a fight between Batman and Darth Vader, the winner would be Chuck Norris.",
    "In a recent survey it was discovered the 94% of American women lost their virginity to Chuck Norris. The other 6% were incredibly fat or ugly.",
    "In a tagteam match, Chuck Norris was teamed with Hulk Hogan against King Kong Bundy and Andre The Giant. He pinned all 3 at the same time.",
    "In an act of great philanthropy, Chuck made a generous donation to the American Cancer Society. He donated 6,000 dead bodies for scientific research.",
    "In honor of Chuck Norris, all McDonald's in Texas have an even larger size than the super-size. When ordering, just ask to be Chucksized.",
    "In the Bible, Jesus turned water into wine. But then Chuck Norris turned that wine into beer.",
    "In the Words of Julius Caesar, \"Veni, Vidi, Vici, Chuck Norris\". Translation: I came, I saw, and I was roundhouse-kicked inthe face by Chuck Norris.",
    "In the X-Men movies, none of the X-Men super-powers are done with special effects. Chuck Norris is the stuntman for every character.",
    "In the first Jurassic Park movie, the Tyrannosaurus Rex wasn't chasing the jeep. Chuck Norris was chasing the Tyrannosaurus AND the jeep.",
    "It takes Chuck Norris 20 minutes to watch 60 Minutes.",
    "Jack Bauer tried to use his detailed knowledge of torture techniques, but to no avail: Chuck Norris thrives on pain. Chuck Norris then ripped off Jack Bauer's arm and beat him to death with it. Game, set, match.",
    "Jesus can walk on water, but Chuck Norris can swim through land.",
    "Love does not hurt. Chuck Norris does.",
    "MacGyver can build an airplane out of gum and paper clips, but Chuck Norris can roundhouse-kick his head through a wall and take it.",
    "Most people have 23 pairs of chromosomes. Chuck Norris has 72... and they're all poisonous.",
    "Mr. T pities the fool. Chuck Norris rips the fool's head off.",
    "Nagasaki never had a bomb dropped on it. Chuck Norris jumped out of a plane and punched the ground",
    "No one has ever spoken during review of Chuck Norris' code and lived to tell about it.",
    "No statement can catch the ChuckNorrisException.",
    "Noah was the only man notified before Chuck Norris relieved himself in the Atlantic Ocean.",
    "On his birthday, Chuck Norris randomly selects one lucky child to be thrown into the sun.",
    "On the set of Walker Texas Ranger Chuck Norris brought a dying lamb back to life by nuzzling it with his beard. As the onlookers gathered, the lamb sprang to life. Chuck Norris then roundhouse kicked it, killing it instantly. This was just to prove that the good Chuck givet",
    "Once Chuck Norris and Superman had a competition. The loser had to wear his underwear over his pants.",
    "Once you go Norris, you are physically unable to go back.",
    "One day Chuck Norris walked down the street with a massive erection. There were no survivors.",
    "One time, Chuck Norris accidentally stubbed his toe. It destroyed the entire state of Ohio.",
    "Only Chuck Norris can prevent forest fires.",
    "Only Chuck Norris shuts down websites without due process, not SOPA or PIPA.",
    "Paper beats rock, rock beats scissors, and scissors beats paper, but Chuck Norris beats all 3 at the same time.",
    "Pluto is actually an orbiting group of British soldiers from the American Revolution who entered space after the Chuck gave them a roundhouse kick to the face.",
    "Product Owners never argue with Chuck Norris after he demonstrates the DropKick feature.",
    "Project managers never ask Chuck Norris for estimations... ever.",
    "Saddam Hussein was not found hiding in a \"hole.\" Saddam was roundhouse-kicked in the head by Chuck Norris in Kansas, which sent him through the earth, stopping just short of the surface of Iraq.",
    "Science Fact: Roundhouse kicks are comprised primarily of an element called Chucktanium.",
    "Some kids play Kick the can. Chuck Norris played Kick the keg.",
    "Some people ask for a Kleenex when they sneeze, Chuck Norris asks for a body bag.",
    "Someone once videotaped Chuck Norris getting pissed off. It was called Walker: Texas Chain Saw Masacre.",
    "Sticks and stones may break your bones, but a Chuck Norris glare will liquefy your kidneys.",
    "Superman once watched an episode of Walker, Texas Ranger. He then cried himself to sleep.",
    "Teenage Mutant Ninja Turtles is based on a true story: Chuck Norris once swallowed a turtle whole, and when he crapped it out, the turtle was six feet tall and had learned karate.",
    "The 1972 Miami Dolphins lost one game, it was a game vs. Chuck Norris and three seven year old girls. Chuck Norris won with a roundhouse-kick to the face in overtime.",
    "The Bible was originally titled \"Chuck Norris and Friends\"",
    "The Chuck Norris Eclipse plugin made alien contact.",
    "The Chuck Norris military unit was not used in the game Civilization 4, because a single Chuck Norris could defeat the entire combined nations of the world in one turn.",
    "The First Law of Thermodynamics states that energy can neither be created nor destroyed... unless it meets Chuck Norris.",
    "The Manhattan Project was not intended to create nuclear weapons, it was meant to recreate the destructive power in a Chuck Norris Roundhouse Kick. They didn't even come close.",
    "The US did not boycott the 1980 Summer Olympics in Moscow due to political reasons: Chuck Norris killed the entire US team with a single round-house kick during TaeKwonDo practice.",
    "The air around Chuck Norris is always a balmy 78 degrees.",
    "The chemical formula for the highly toxic cyanide ion is CN-. These are also Chuck Norris' initials. This is not a coincidence.",
    "The class object inherits from Chuck Norris",
    "The grass is always greener on the other side, unless Chuck Norris has been there. In that case the grass is most likely soaked in blood and tears.",
    "The movie \"Delta Force\" was extremely hard to make because Chuck had to downplay his abilities. The first few cuts were completely unbelievable.",
    "The only pattern Chuck Norris knows is God Object.",
    "The only sure things are Death and Taxes and when Chuck Norris goes to work for the IRS, they'll be the same thing.",
    "The opening scene of the movie \"Saving Private Ryan\" is loosely based on games of Dodgeball Chuck Norris played in second grade.",
    "The original draft of The Lord of the Rings featured Chuck Norris instead of Frodo Baggins. It was only 5 pages long, as Chuck roundhouse-kicked Sauron's ass halfway through the first chapter.",
    "The phrase 'break a leg' was originally coined by Chuck Norris's co-stars in Walker, Texas Ranger as a good luck charm, indicating that a broken leg might be the worst extent of their injuries. This never proved to be the case.",
    "The phrase 'dead ringer' refers to someone who sits behind Chuck Norris in a movie theater and forgets to turn their cell phone off.",
    "The pie scene in \"American Pie\" is based on a dare Chuck Norris took when he was younger. However, in Chuck Norris' case, the \"pie\" was the molten crater of an active volcano.",
    "The truth will set you free. Unless Chuck Norris has you, in which case, forget it buddy!",
    "The word 'Kill' was invented by Chuck Norris. Other words were 'Die', 'Beer', and 'What'.",
    "There are no races, only countries of people Chuck Norris has beaten to different shades of black and blue.",
    "There are no steroids in baseball. Just players Chuck Norris has breathed on.",
    "There are no such things as tornados. Chuck Norris just hates trailer parks.",
    "There are only two things that can cut diamonds: other diamonds, and Chuck Norris.",
    "There is endless debate about the existence of the human soul. Well it does exist and Chuck Norris finds it delicious.",
    "There is in fact an 'I' in Norris, but there is no 'team'. Not even close.",
    "There is no such thing as a lesbian, just a woman who has never met Chuck Norris.",
    "Think of a hot woman. Chuck Norris did her.",
    "Time waits for no man. Unless that man is Chuck Norris.",
    "To Chuck Norris, everything contains a vulnerability.",
    "Using his trademark roundhouse kick, Chuck Norris once made a field goal in RJ Stadium in Tampa Bay from the 50 yard line of Qualcomm stadium in San Diego.",
    "When Chuck Norris does a push-up, he isn't lifting himself up, he's pushing the Earth down.",
    "When Chuck Norris falls in water, Chuck Norris doesn't get wet. Water gets Chuck Norris.",
    "When Chuck Norris goes to out to eat, he orders a whole chicken, but he only eats its soul.",
    "When Chuck Norris is web surfing websites get the message \"Warning: Internet Explorer has deemed this user to be malicious or dangerous. Proceed?\".",
    "When Chuck Norris sends in his taxes, he sends blank forms and includes only a picture of himself, crouched and ready to attack. Chuck Norris has not had to pay taxes, ever.",
    "When Chuck Norris throws exceptions, it's across the room.",
    "When Chuck Norris was born, he immediately had sex with the first nurse he saw. He was her first. She was his third. That afternoon.",
    "When God said, \"let there be light\", Chuck Norris said, \"say 'please'.\"",
    "When J. Robert Oppenheimer said \"I am become death, the destroyer Of worlds\", He was not referring to the atomic bomb. He was referring to the Chuck Norris halloween costume he was wearing.",
    "When Steven Seagal kills a ninja, he only takes its hide. When Chuck Norris kills a ninja, he uses every part.",
    "When in a bar, you can order a drink called a \"Chuck Norris\". It is also known as a \"Bloody Mary\", if your name happens to be Mary.",
    "When taking the SAT, write \"Chuck Norris\" for every answer. You will score over 8000.",
    "When you're Chuck Norris, anything + anything is equal to 1. One roundhouse kick to the face.",
    "While urinating, Chuck Norris is easily capable of welding titanium.",
    "Who let the dogs out? Chuck Norris let the dogs out... and then roundhouse kicked them through an Oldsmobile.",
    "With Chuck Norris P = NP. There's no nondeterminism with Chuck Norris decisions.",
    "With the rising cost of gasoline, Chuck Norris is beginning to worry about his drinking habit.",
    "Wo hu cang long. The translation from Mandarin Chinese reads: \"Crouching Chuck, Hidden Norris\""
  };
  private static final Random RANDOM = new Random();

  public static String random() {
    return QUOTES[RANDOM.nextInt(QUOTES.length)];
  }
}
