name: Build and Push Windows Images (2022)

on:
  push:
    branches:
      - master

jobs:
  build-push:
    name: Build and Push
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        image-name: ['docker-registry-windows']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dockerize
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker build -t marcnuri/${{ matrix.image-name }}:ltsc2022 .\\${{ matrix.image-name }}\\
          docker images
          docker push marcnuri/${{ matrix.image-name }}:ltsc2022
