name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-name: [
          'chuck-norris',
          'jokes',
          'golang-1.16-java11',
          'golang-1.17-java11',
          'golang-1.18-java17',
          'golang-1.19-java17',
          'golang-1.20-java17',
          'golang-1.21-java17',
          'openssh-server'
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dockerize
        uses: manusa/actions-publish-docker@v1.1.0
        with:
          name: marcnuri/${{ matrix.image-name }}
          dockerfile path: ./${{ matrix.image-name }}/
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
